import { MODEL_SUPPLEMENTARY_EXTRA } from './modelLibrary.supplementary-EXTRA';

import type { Model } from './modelLibrary.types';

const TEXT_INPUT_DESCRIPTION =
  'Natural language prompts, instructions, and context';
const TEXT_OUTPUT_DESCRIPTION =
  'Natural language responses, code, and structured text outputs';
const QWEN3_RELEASE_DATE = '2025-04-29';
/**
 * Supplementary metadata keyed by model id.
 * The Helix /v1/models endpoint returns only id, root, max_model_len, created, owned_by.
 * Everything else needed to render a ModelCard lives here.
 */
export const MODEL_SUPPLEMENTARY: Record<string, Partial<Model>> = {
  'gemma-4-26b-a4b-it': {
    description:
      "Google's Gemma 4 26B delivers elite reasoning and native vision with a massive 100K context window — the perfect high-efficiency choice for complex agents and low-latency production workflows.",
    descriptionShort:
      'Elite reasoning and native vision with a 100K context window, optimised for agents and production workflows.',
    useCaseTags: [
      {
        label: 'Multimodal Analysis',
        description:
          'Reading large PDFs with images/charts or analyzing short video clips',
      },
      {
        label: 'AI Agent',
        description:
          'Autonomously executing complex workflows using native tool-calling.',
      },
      {
        label: 'Advanced Reasoning',
        description:
          'Solving difficult logic, math, and science problems via thinking mode.',
      },
      {
        label: 'Coding',
        description: 'Coding, Reviewing & Debugging of large codebases',
      },
      {
        label: 'Chatbots',
        description:
          'Build conversational AI applications with multi-turn dialogue.',
      },
      {
        label: 'Structured Data Extraction',
        description:
          'Extract information from documents and unstructured text into structured formats like JSON or CSV.',
      },
      {
        label: 'Multilingual Translation',
        description:
          'Translate text between multiple languages with high accuracy and fluency.',
      },
    ],
    inputModes: [
      {
        label: 'Text',
        description: TEXT_INPUT_DESCRIPTION,
      },
      {
        label: 'Image',
        description:
          'Static image inputs for visual understanding, document analysis, and multimodal reasoning',
      },
      {
        label: 'Video',
        description: 'Frame-by-frame video inputs (up to 60 s at 1 fps)',
      },
    ],
    outputModes: [
      {
        label: 'Text',
        description: TEXT_OUTPUT_DESCRIPTION,
      },
    ],
    contextLengthK: 256,
    isServerless: true,
    parametersB: 26,
    priceInputPerMillion: 0.2,
    priceOutputPerMillion: 0.5,
    providerLogo: 'Google',
    providerName: 'Google',
    releasedAt: '2026-04-02',
    title: 'Gemma 4 26B',
    updatedAt: '2025-04-10',
    supportedLanguages: [
      'Afrikaans',
      'Arabic',
      'Armenian',
      'Assamese',
      'Bengali',
      'Bulgarian',
      'Catalan',
      'Chinese',
      'Croatian',
      'Czech',
      'Danish',
      'Dutch',
      'English',
      'Estonian',
      'Faroese',
      'Finnish',
      'French',
      'Galician',
      'Georgian',
      'German',
      'Greek',
      'Gujarati',
      'Hebrew',
      'Hindi',
      'Hungarian',
      'Icelandic',
      'Indonesian',
      'Irish',
      'Italian',
      'Japanese',
      'Kannada',
      'Kazakh',
      'Korean',
      'Latvian',
      'Lithuanian',
      'Macedonian',
      'Malay',
      'Malayalam',
      'Maltese',
      'Marathi',
      'Nepali',
      'Norwegian',
      'Oromo',
      'Persian',
      'Polish',
      'Portuguese',
      'Punjabi',
      'Romanian',
      'Russian',
      'Serbian',
      'Sinhala',
      'Slovak',
      'Slovenian',
      'Spanish',
      'Swahili',
      'Swedish',
      'Tamil',
      'Telugu',
      'Thai',
      'Turkish',
      'Ukrainian',
      'Urdu',
      'Uzbek',
      'Vietnamese',
      'Welsh',
      'Yoruba',
    ],
  },
  ...MODEL_SUPPLEMENTARY_EXTRA,
  'qwen3-4b': {
    description:
      'Qwen3 4B is a compact yet highly capable instruction-tuned model from Alibaba, optimised for fast inference on resource-constrained environments.',
    descriptionShort:
      'Compact instruction-tuned model from Alibaba, optimised for fast inference on resource-constrained environments.',
    useCaseTags: [
      {
        label: 'AI Agent',
        description:
          'Orchestrate autonomous agents for complex task automation',
      },
      {
        label: 'Coding',
        description: 'Generate, complete, and debug code across languages',
      },
      {
        label: 'Math',
        description: 'Solve mathematical problems and reasoning tasks',
      },
    ],
    inputModes: [
      {
        label: 'Text',
        description: TEXT_INPUT_DESCRIPTION,
      },
    ],
    outputModes: [
      {
        label: 'Text',
        description: TEXT_OUTPUT_DESCRIPTION,
      },
    ],
    contextLengthK: 32,
    isServerless: true,
    parametersB: 4,
    priceInputPerMillion: 0.05,
    priceOutputPerMillion: 0.1,
    providerLogo: 'alibaba',
    providerName: 'Qwen',
    releasedAt: QWEN3_RELEASE_DATE,
    title: 'Qwen3 4B',
    updatedAt: '2025-11-01',
    supportedLanguages: [
      'Afrikaans',
      'Arabic',
      'Armenian',
      'Assamese',
      'Asturian',
      'Awadhi',
      'Balinese',
      'Banjar',
      'Bashkir',
      'Basque',
      'Belarusian',
      'Bengali',
      'Bhojpuri',
      'Bosnian',
      'Bulgarian',
      'Burmese',
      'Catalan',
      'Cebuano',
      'Chhattisgarhi',
      'Chinese',
      'Croatian',
      'Czech',
      'Danish',
      'Dari',
      'Dutch',
      'Eastern Yiddish',
      'English',
      'Estonian',
      'Faroese',
      'Finnish',
      'French',
      'Friulian',
      'Galician',
      'Georgian',
      'German',
      'Greek',
      'Gujarati',
      'Haitian',
      'Hebrew',
      'Hindi',
      'Hungarian',
      'Icelandic',
      'Iloko',
      'Indonesian',
      'Irish',
      'Italian',
      'Japanese',
      'Javanese',
      'Kabuverdianu',
      'Kannada',
      'Kazakh',
      'Khmer',
      'Korean',
      'Lao',
      'Latvian',
      'Ligurian',
      'Limburgish',
      'Lithuanian',
      'Lombard',
      'Luxembourgish',
      'Macedonian',
      'Magahi',
      'Maithili',
      'Malay',
      'Malayalam',
      'Maltese',
      'Marathi',
      'Minangkabau',
      'Nepali',
      'North Azerbaijani',
      'Northern Uzbek',
      'Norwegian Bokmål',
      'Norwegian Nynorsk',
      'Occitan',
      'Oriya',
      'Pangasinan',
      'Papiamento',
      'Persian',
      'Polish',
      'Portuguese',
      'Punjabi',
      'Romanian',
      'Russian',
      'Sardinian',
      'Serbian',
      'Sicilian',
      'Silesian',
      'Sindhi',
      'Sinhala',
      'Slovak',
      'Slovenian',
      'Spanish',
      'Sundanese',
      'Swahili',
      'Swedish',
      'Tagalog',
      'Tajik',
      'Tamil',
      'Tatar',
      'Telugu',
      'Thai',
      'Tok Pisin',
      'Tosk Albanian',
      'Turkish',
      'Ukrainian',
      'Urdu',
      'Venetian',
      'Vietnamese',
      'Waray',
      'Welsh',
    ],
  },
  'qwen3-8b': {
    description:
      'Qwen3 8B is a high-efficiency instruction-tuned model from Alibaba with strong reasoning capabilities across code, math, and multilingual tasks.',
    descriptionShort:
      'High-efficiency model from Alibaba with strong reasoning across code, math, and multilingual tasks.',
    useCaseTags: [
      {
        label: 'AI Agent',
        description:
          'Orchestrate autonomous agents for complex task automation',
      },
      {
        label: 'Coding',
        description: 'Generate, complete, and debug code across languages',
      },
      {
        label: 'Math',
        description: 'Solve mathematical problems and reasoning tasks',
      },
    ],
    inputModes: [
      {
        label: 'Text',
        description: TEXT_INPUT_DESCRIPTION,
      },
    ],
    outputModes: [
      {
        label: 'Text',
        description: TEXT_OUTPUT_DESCRIPTION,
      },
    ],
    contextLengthK: 128,
    isServerless: true,
    parametersB: 8,
    priceInputPerMillion: 0.1,
    priceOutputPerMillion: 0.3,
    providerLogo: 'alibaba',
    providerName: 'Qwen',
    releasedAt: QWEN3_RELEASE_DATE,
    title: 'Qwen3 8B',
    updatedAt: '2025-12-15',
    supportedLanguages: [
      'Afrikaans',
      'Arabic',
      'Armenian',
      'Assamese',
      'Asturian',
      'Awadhi',
      'Balinese',
      'Banjar',
      'Bashkir',
      'Basque',
      'Belarusian',
      'Bengali',
      'Bhojpuri',
      'Bosnian',
      'Bulgarian',
      'Burmese',
      'Catalan',
      'Cebuano',
      'Chhattisgarhi',
      'Chinese',
      'Croatian',
      'Czech',
      'Danish',
      'Dari',
      'Dutch',
      'Eastern Yiddish',
      'English',
      'Estonian',
      'Faroese',
      'Finnish',
      'French',
      'Friulian',
      'Galician',
      'Georgian',
      'German',
      'Greek',
      'Gujarati',
      'Haitian',
      'Hebrew',
      'Hindi',
      'Hungarian',
      'Icelandic',
      'Iloko',
      'Indonesian',
      'Irish',
      'Italian',
      'Japanese',
      'Javanese',
      'Kabuverdianu',
      'Kannada',
      'Kazakh',
      'Khmer',
      'Korean',
      'Lao',
      'Latvian',
      'Ligurian',
      'Limburgish',
      'Lithuanian',
      'Lombard',
      'Luxembourgish',
      'Macedonian',
      'Magahi',
      'Maithili',
      'Malay',
      'Malayalam',
      'Maltese',
      'Marathi',
      'Minangkabau',
      'Nepali',
      'North Azerbaijani',
      'Northern Uzbek',
      'Norwegian Bokmål',
      'Norwegian Nynorsk',
      'Occitan',
      'Oriya',
      'Pangasinan',
      'Papiamento',
      'Persian',
      'Polish',
      'Portuguese',
      'Punjabi',
      'Romanian',
      'Russian',
      'Sardinian',
      'Serbian',
      'Sicilian',
      'Silesian',
      'Sindhi',
      'Sinhala',
      'Slovak',
      'Slovenian',
      'Spanish',
      'Sundanese',
      'Swahili',
      'Swedish',
      'Tagalog',
      'Tajik',
      'Tamil',
      'Tatar',
      'Telugu',
      'Thai',
      'Tok Pisin',
      'Tosk Albanian',
      'Turkish',
      'Ukrainian',
      'Urdu',
      'Venetian',
      'Vietnamese',
      'Waray',
      'Welsh',
    ],
  },
  'qwen3-embedding-4b': {
    description:
      'Qwen3 Embedding 4B is a state-of-the-art multilingual text embedding model from Alibaba, optimised for semantic search, retrieval-augmented generation, and similarity tasks across 100+ languages.',
    descriptionShort:
      'State-of-the-art multilingual embedding model from Alibaba, optimised for semantic search and RAG across 100+ languages.',
    useCaseTags: [
      {
        label: 'RAG',
        description:
          'Power retrieval-augmented generation pipelines with high-quality semantic search',
      },
      {
        label: 'Text Embeddings',
        description:
          'Encode text into dense vectors for semantic similarity and search',
      },
      {
        label: 'Reranking',
        description:
          'Reorder candidate documents to improve retrieval precision',
      },
    ],
    inputModes: [
      {
        label: 'Text',
        description:
          'Natural language text to encode into dense vector representations',
      },
    ],
    outputModes: [
      {
        label: 'Embeddings',
        description:
          'High-dimensional dense vector representations for semantic search, retrieval, and similarity tasks',
      },
    ],
    contextLengthK: 32,
    isServerless: false,
    parametersB: 4,
    priceInputPerMillion: 0.03,
    priceOutputPerMillion: 0.0,
    providerLogo: 'alibaba',
    providerName: 'Qwen',
    releasedAt: '2025-06-05',
    title: 'Qwen3 Embedding 4B',
    updatedAt: QWEN3_RELEASE_DATE,
    supportedLanguages: [
      'Afrikaans',
      'Arabic',
      'Armenian',
      'Assamese',
      'Asturian',
      'Awadhi',
      'Balinese',
      'Banjar',
      'Bashkir',
      'Basque',
      'Belarusian',
      'Bengali',
      'Bhojpuri',
      'Bosnian',
      'Bulgarian',
      'Burmese',
      'Catalan',
      'Cebuano',
      'Chhattisgarhi',
      'Chinese',
      'Croatian',
      'Czech',
      'Danish',
      'Dari',
      'Dutch',
      'Eastern Yiddish',
      'English',
      'Estonian',
      'Faroese',
      'Finnish',
      'French',
      'Friulian',
      'Galician',
      'Georgian',
      'German',
      'Greek',
      'Gujarati',
      'Haitian',
      'Hebrew',
      'Hindi',
      'Hungarian',
      'Icelandic',
      'Iloko',
      'Indonesian',
      'Irish',
      'Italian',
      'Japanese',
      'Javanese',
      'Kabuverdianu',
      'Kannada',
      'Kazakh',
      'Khmer',
      'Korean',
      'Lao',
      'Latvian',
      'Ligurian',
      'Limburgish',
      'Lithuanian',
      'Lombard',
      'Luxembourgish',
      'Macedonian',
      'Magahi',
      'Maithili',
      'Malay',
      'Malayalam',
      'Maltese',
      'Marathi',
      'Minangkabau',
      'Nepali',
      'North Azerbaijani',
      'Northern Uzbek',
      'Norwegian Bokmål',
      'Norwegian Nynorsk',
      'Occitan',
      'Oriya',
      'Pangasinan',
      'Papiamento',
      'Persian',
      'Polish',
      'Portuguese',
      'Punjabi',
      'Romanian',
      'Russian',
      'Sardinian',
      'Serbian',
      'Sicilian',
      'Silesian',
      'Sindhi',
      'Sinhala',
      'Slovak',
      'Slovenian',
      'Spanish',
      'Sundanese',
      'Swahili',
      'Swedish',
      'Tagalog',
      'Tajik',
      'Tamil',
      'Tatar',
      'Telugu',
      'Thai',
      'Tok Pisin',
      'Tosk Albanian',
      'Turkish',
      'Ukrainian',
      'Urdu',
      'Venetian',
      'Vietnamese',
      'Waray',
      'Welsh',
    ],
  },
};
